version: 0.2
phases:
  pre_build:
    commands:
      - echo "Getting CodeArtifact authorization token"
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain test-cb --query authorizationToken --output text`
      - echo "Token obtained successfully"
  build:
    commands:
      - echo "Building static binary artifact"
      - mkdir -p artifacts
      - echo "Static binary content version 1.0 - $(date)" > artifacts/static-binary.txt
      - echo "Additional file for testing" > artifacts/readme.txt
      - tar -czf static-binary-1.0.tar.gz artifacts/
      - ls -la static-binary-1.0.tar.gz
  post_build:
    commands:
      - echo "Uploading package to CodeArtifact"
      - |
        aws codeartifact publish-package-version \
          --domain test-cb \
          --repository test-repo-for-CodeArtifact \
          --format generic \
          --package static-binary \
          --package-version "1.0" \
          --asset-content fileb://static-binary-1.0.tar.gz \
          --asset-name "static-binary-1.0.tar.gz" \
          --asset-sha256 $(sha256sum static-binary-1.0.tar.gz | cut -d' ' -f1) || echo "Package upload failed or already exists"
      - echo "Also uploading to S3 as backup"
      - aws s3 cp static-binary-1.0.tar.gz s3://test-static-binaries-bucket/packages/static-binary/1.0/
artifacts:
  files:
    - static-binary-1.0.tar.gz
